# Remote image
IMAGE=hldtux/ndevkit
# Local image
#IMAGE=ndevkit
TAG=latest
# Forcing amd64 arch
DOCKER_DEFAULT_PLATFORM=linux/amd64

docker:
	docker build . -t ${IMAGE}

shell:	docker
	docker run -it --rm -v `pwd`:/tmp/workdir -w /tmp/workdir ${IMAGE} bash

push:
	docker push ${IMAGE}:${TAG}

