# Directory to build the toolchain into
LOCALDIR=$(shell cd $(dir $(lastword $(MAKEFILE_LIST))) && pwd)/local

# There are faster GNU mirror for downloading the toolchain
GNU_MIRROR=ftp://ftp.gnu.org/gnu
# GNU_MIRROR=http://fr.mirror.babylon.network/gnu

# Compilation override
HOSTOPTS=

# Default input config for gngeo
GNGEO_CFG=$(HOME)/.gngeo/gngeorc
define GNGEO_DEFAULT_INPUT_SETTINGS =
scale 3
joystick true
p1control A=K97,B=K115,C=K113,D=K119,START=K49,COIN=K51,UP=K82,DOWN=K81,LEFT=K80,RIGHT=K79,A=J0B0,B=J0B1,C=J0B2,D=J0B3,START=J0B9,COIN=J0B8,UP=J0a3,DOWN=J0a3,LEFT=J0A0,RIGHT=J0A0
endef

# MinGW configuration bits
# Absolute path are required here
GNGEO_INSTALL_PATH=
SDL2_DLL=
# Variable below are autodetected
MINGW_GCC=
ZLIB1_DLL=