# Directory to build the toolchain into
LOCALDIR=$(shell cd $(dir $(lastword $(MAKEFILE_LIST))) && pwd)/local

# There are faster GNU mirror for downloading the toolchain
GNU_MIRROR=ftp://ftp.gnu.org/gnu
# GNU_MIRROR=http://mirror-fr1.bbln.org/gnu

# Compilation override
HOSTOPTS=

